
name: sose03
services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: gordluser
      POSTGRES_PASSWORD: gordlpassword
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d